Feat/calendar component
wafflestudio20-5/team9-web pull request #11
Opened 2023-01-04 16:57 UTC by emilyyoon3107

2023-01-05 02:51 UTC, aylee2008 commented on lib/utils/calculateDate.ts
> +export const getCalendarDates = (
이 부분은 나중에 시작 년월일, 끝 년월일을 백엔드에 api 요청으로 보내주면 자동으로 받아오게끔 바꾸는 게 나을 것 같아요. 물론 지금 pr에서는 안 고쳐도 될 듯 합니당

2023-01-05 03:18 UTC, aylee2008 commented on lib/utils/calculateDate.ts
> +export const getCalendarDates = (
for문을 30번 도는게 너무 비효율적일 것 같아서요. from은 firstDayincurrmonth 받고, 그것의 요일을 계산해서 그 주 월요일만 계산하면 되고, to도 마찬가지로 그 주 일요일만 계산하면 돼서 훨씬 간단할 것 같아요.

아 그리고, from, to를 api에다 보내면 현재 계산 과정보다 좀 더 간단해지지 않을까요? 그냥 Date 형태로 보내면 돼서 굳이 prevMonth와 lastDateInPrevMonth 계산할 필요 없이 `firstDayInCurrMonth - firstDayInCurrMonth.day()`같은 형식으로 좀 더 간단하게 할 수 있지 않을까 싶어서 comment 달아봤습니다!

2023-01-05 09:13 UTC, Limchansol requested changes
- 와 뭔가 계산하는 부분이 많았던 것 같네요...!
- `useEffect` 디펜던시에는 그 안에서 참조하는 변수와 함수가 전부 들어가있는 게 옳은 방향이라고 알고 있어서 `changeToToday`도 넣어놓긴 했습니다만 사실 저도 이 부분은 명확하게 아는 것이 아니라... 일단 별 문제 없어보이니 괜찮을 것 같긴 합니다!
- 자잘한 것 몇 개와 논의하고 싶은 부분에 코멘트 달아두었습니다!

2023-01-05 09:13 UTC, Limchansol commented on components/Header/CalendarModal.module.scss
> +    height: 250px;
이거 임의로 대충 설정해놓았던 건데 잘 바꿔주셨네요!

2023-01-05 09:37 UTC, emilyyoon3107 commented on components/MiniCalendar.tsx
> +                                setDayNow(index % 7);
아ㅏ 이 부분을 생각을 못했네요! 저도 주소창을 바로 바꾸는게 더 효율적일 것 같습니다.

2023-01-05 16:57 UTC, aylee2008 commented on components/MiniCalendar.tsx
> +                                setDayNow(index % 7);
저도요..!!

2023-01-05 17:34 UTC, emilyyoon3107 commented
- 더 찾아보니 `Date` 타입으로 생각보다 많은 연산을 처리할 수 있어서 날짜 계산이 훨씬 간단해졌습니다!! 그냥 날짜를 음수로 넣어도 `setDate()`하면 알아서 year랑 month까지 필요한대로 맞춰주더라고요.... 그래서 `/utils/calculateDate`에 추가했던 내용도 필요가 없어져 지웠습니다.
- 각 버튼 누를 때 context를 변경하는 게 아니라 redirect하도록 바꿨습니다.
- 그 외 자잘한 변화들 일부 있습니다 (주로 코드 styling)

2023-01-06 10:36 UTC, aylee2008 approved these changes

2023-01-06 14:27 UTC, merged