Header
wafflestudio20-5/team9-web pull request #4
Opened 2022-12-18 08:44 UTC by Limchansol

1. 헤더가 위치를 우선적으로 잡아야 다른 작업이 조금이나마 수월할 듯해서 일단 구조만 잡았습니다.
2. 로그인이나 유저 계정 설정, 날짜 변경 등의 헤더 기능은 아직 구현하지 않은 상태이고, 이 브랜치 머지한 이후에 `header-details` 브랜치 하나 다시 파서 기능 마저 구현할 생각입니다.
3. 페이지 주소는 우선 각각 `월별 캘린더(기본) "/", 일정 페이지 "/schedule"`로 상정하고 구현했습니다. 일단 기본 페이지를 월별 캘린더로 잡았는데, index("/")에 해당하는 페이지를 안내 페이지처럼 따로 만들고 "/month", "/schedule" 등으로 각 캘린더 페이지를 라우팅하는 방법도 고려해볼 수 있을 것 같습니다. 구글 캘린더는 로그인하지 않으면 사용이 불가능한 서비스인 것 같아서 아예 첫 페이지를 안내 페이지로 잡는 것도 괜찮을 것 같긴 합니다. 이 부분에 대해 의견 주시면 감사하겠습니다.
5. 필수 스펙 중 사용자 계정 페이지가 있습니다. 구글 캘린더에서는 우측 상단의 사용자 버튼을 누르면 팝업이 뜨는데 이걸 그대로 구현하는 것과, 아예 새로운 페이지로 이동하도록 변경하는 것 중 어느편이 나을까요?
6. 헤더 아이콘들 이미지에 svg를 쓰려다가 에러를 못 해결하는 바람에 우선 png로 변경했습니다.
7. 커밋 메시지 컨벤션 중 `style`은 코드 포맷팅 관련된 카테고리인 것 같아서, css 관련 커밋은 `design` 카테고리로 분류했습니다. (참고: https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-git-%EC%BB%A4%EB%B0%8B%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)
8. 리뷰해주시면 수정할 부분 수정한 이후에 제가 머지하거나 PR 리뷰 다시 걸거나 해보겠습니다!

2022-12-18 10:20 UTC, aylee2008 reviewed
comment file별로 달아놓았으니 확인 부탁드려요.
png 파일은 모두 svg로 바꾸는 게 좋을 듯 합니다..!

2022-12-18 10:20 UTC, aylee2008 commented on @types/index.d.ts
> +declare module '*.png' {
아무래도 png보다는 svg가 나을 것 같아요.

저는 아래와 같이 module 선언하고 import해서 svg import했는데, 한번 해보시겠어요?
```
declare module '*.svg' {
    const content: any;
    export default content;
}
```
```
import logo from '../resources/waffle-logo-1.svg';
```

2022-12-18 10:20 UTC, aylee2008 commented on components/Header.tsx
> +        {/* 사이드바 아이콘 */}
코드 상에서 한글은 되도록이면 안 쓰는 게 나을 것 같습니다.
저도 한글 참 사랑하지만.. 인코딩 때문에 너무 많은 이슈들이 발생해서..
모두 **영어로** 고쳐주시는 게 좋을 것 같아요.
@emilyyoon3107 님도 함께 참고해주시면 감사하겠습니다.

2022-12-18 10:20 UTC, aylee2008 commented on pages/index.js
> -    return <div className={styles.App}></div>;
흠 이건 아까 위에서 얘기한 것처럼 .prettierrc를 바꾸면서 생긴 변화인 것 같네요.
단순히 tab 4가 너무 큰 것 같아서 2로 변경하신 건가요??

2022-12-18 10:25 UTC, aylee2008 commented
아 질문을 남겨주셨네요. 3.의 경우, 로그인이 되어 있는 경우에는 "/"를 "/month"로 보내고, 아니라면 로그인 페이지나 안내 페이지로 보내는 게 좋을 것 같아요. 4.의 경우는 팝업이 좋을 것 같습니다..!

2022-12-18 10:27 UTC, aylee2008 commented
resolve 후 re-request 걸어주세요!

2022-12-18 11:57 UTC, Limchansol commented on .prettierrc
>  {
이거 아마 제 로컬에서 .prettierrc이 에러가 뜨고 포맷팅이 잘 안 되길래 이것저것 시도해보다가 변경사항이 그대로 남은 것 같아요...!
그것과는 별개로 혹시 들여쓰기 4칸이 일반적인가요?!

2022-12-18 12:31 UTC, fivessun5 commented on .prettierrc
>  {
갑자기 궁금해져서 저도 찾아보는데 엄청 뜨거운 화두인거 같네요 ㅋㅋㅋ
기존엔 4칸이 전통인데 최근에는 2칸도 대세로 올라오는 중이라는 글들이 우수수...
https://stackoverflow.com/questions/26664143/are-there-practical-or-technical-advantages-to-using-2-space-vs-4-space-indents

2022-12-18 12:37 UTC, fivessun5 commented on components/Header.tsx
> +import { useRouter } from 'next/router';
https://seohyun0120.tistory.com/entry/ESLint-importsexports-구문의-순서-자동-정렬하기
ESLint 에서 import 순서 자동 정렬 기능을 제공하는데 한번 써보는 건 어떨까요?? 일일히 정렬하는 것만큼 또 귀찮은게 없으니...

2022-12-18 13:45 UTC, emilyyoon3107 requested changes
많은 부분들을 이미 얘기해주셔서 제가 얘기할 게 딱히 없네요!

prittierrc는 어떤 오류가 떴는지 모르겠지만... 4칸이든 2칸이든 정해놓는 게 좋겠습니다! 저도 전통적으로 4칸이라고 알고 있는데 2칸이 길이가 애매하게 걸리는 일은 더 적더라고요..

2022-12-18 13:45 UTC, emilyyoon3107 commented
3. 라우팅 부분은 "/"는 기본적으로 로그인 페이지로 하되, 로그인이 되어 있으면 자동으로 "/month"로 넘어가게 하는 게 좋을 것 같습니다! 현재 구글 캘린더도 그런 방식인 것 같구요.

4. 사용자 계정 페이지라는 게 계정 정보 수정이나 이런 부분도 포함해야 한다면 별도의 페이지가, 그런 게 아니라 정보 표시 정도만이라면 팝업이 좋을 것 같습니다. 현재 구글 캘린더도 그렇게 되어 있고요.

2022-12-18 14:22 UTC, Limchansol commented on .prettierrc
>  {
아하... 지금까지 봐온 예시코드가 대부분 2칸이어서 전 지금까지 자연스레 js는 전부 2칸을 썼는데 4칸도 많이들 쓰는 거였군요

2022-12-18 14:27 UTC, Limchansol commented on @types/index.d.ts
> +declare module '*.png' {
흠 이것도 해봤는데 그때는 에러는 없어졌지만 아예 이미지를 못 불러오고 alt가 대신 떴었어요. 여러번 해보다가 안되겠다 싶어서 png로 바꿨는데 다시 해도 또 alt가 뜨네요ㅠㅠㅠ

2022-12-18 15:38 UTC, Limchansol commented
다른 부분은 모두 수정했고, 태양님이 말씀하신 eslint-plugin-import를 시도해봤는데 적용이 안 된 것인지 별다른 변화가 없어보입니다. 
`npm i --save--dev eslint-plugin-import`, `npm i --save--dev @typescript-eslint/parser eslint-import-resolver-typescript` 해서 플러그인 설치했고, `.eslintrc.js` 파일 설정을 태양님이 주신 링크 참고해서 추가해놓은 상태입니다. 혹시 다른 분들께서 확인 한번 해주실 수 있을까요?

2022-12-19 01:02 UTC, fivessun5 commented on components/Header.tsx
> +import { useRouter } from 'next/router';
저건 예시로 올린 거고, 작동 안하면....유효한 다른 대안을 찾아봐야할 것 같군요...ㅠ  @Limchansol

2022-12-19 05:08 UTC, aylee2008 reviewed
1. prettier 돌린 후 commit하겠습니다!
2. public/manifest.json에서 merge conflict가 해결되지 않았습니다. 제가 고치겠습니다!
3. eslint로 정렬하는 게 잘 동작하지 않네요.. 제가 한번 고치고 commit해 보겠습니다!

2022-12-19 05:42 UTC, aylee2008 commented
아래 이슈들 모두 해결 완료했습니다 :)
> 1. prettier 돌린 후 commit하겠습니다!
> 2. public/manifest.json에서 merge conflict가 해결되지 않았습니다. 제가 고치겠습니다!
> 3. eslint로 정렬하는 게 잘 동작하지 않네요.. 제가 한번 고치고 commit해 보겠습니다!

그리고 prettier랑 eslint 돌리기 쉽게 built-in script 추가해 두었습니다. 앞으로 pull request 날리기 전에 `npm run prettier:fix`로 prettier formatting, `npm run lint:fix`로 eslint 확인 및 formatting 하신 후 pull request 날려주시면 좋을 것 같아요. 그런데 저렇게 했을 때 원래 코드를 확인만 하는 게 아니라 formatting하여 덮어씌우는 거라, 그 부분만 유의해주시면 좋겠네요.

2022-12-19 05:43 UTC, aylee2008 approved these changes

2022-12-19 09:10 UTC, merged