Context
wafflestudio20-5/team9-web pull request #5
Opened 2022-12-19 13:40 UTC by Limchansol

- `SessionContext`와 `DateContext` 추가했습니다.
- 주석에 써놓긴 했지만 차후에 로그인 등을 구현할 때 `SessionContext`에  함수를 추가하게 될 것 같습니다. 기존에 구현한 부분은 건드리지 않을 듯해서 큰 문제는 없을 것 같긴 합니다!
- `DateContext`에서 `value`로 연월일 한번에 묶어서 내려보낼까 고민하다가, 분리해서 내려주는 편이 다른 기능 구현(이전달, 다음달 등)하기에 편할 것 같아서 우선 그렇게 했습니다. 다른 의견 있으시면 가감없이 말씀해주세요!
- 지금 보니까 딱히 건드린 적 없는 `yarn.lock`이 수정되었는데 이건 자동으로 이루어진 일이겠죠...?
- 데이터 타입 규정할 때 일단 `type`을 사용했는데, 사소한 부분이지만 `interface`를 쓸지 `type`을 쓸지 각자 알아서 할지 정해두는 것이 좋을 듯합니다.
- 그외에 수정할 만한 부분이 있다면 알려주세요!

2022-12-19 14:52 UTC, emilyyoon3107 requested changes

2022-12-19 14:52 UTC, emilyyoon3107 commented on contexts/DateContext.tsx
> +            value={{ year, month, date, setYear, setMonth, setDate }}
이건 제가 확실하지 않은데... 원래 context api 만들 때에 value에 useMemo를 걸어서 rerendering을 줄여줬던 걸로 기억하는데 nextjs에서는 안필요하다던가 그런 건가요...?

2022-12-19 15:42 UTC, emilyyoon3107 commented
로컬에서 svg import 에 module not found 가 뜨는 걸로 시작해서 이리저리 뒤적거리다가 발견했는데, 현재 tsconfig 세팅에 몇가지 문제가 있었습니다.
- 일단은 include에 "src"만 되어 있어서 components, pages에는 제대로 적용이 되지 않았던 것 같습니다. (전에는 src 안에 모든 파일을 다 넣어 놨기에 이게 문제가 되지 않았었죠)
- 원래는 recognize all visible `@types` folders 여야 하는데 그게 잘 안되는 모양이더라고요 (제 local에서만 그런 건지는 모르겠습니다...)

결론적으로 해결책을 찾았는데
방법1) tsconfig.json을 지우고 새로 만든 뒤, npm run dev를 하면 nextjs가 알아서 tsconfig를 세팅해줍니다! 
방법2) 1의 tsconfig는 strict:false로 되어 있는 등 커스텀 세팅이 기존에 쓰던 tsconfig랑 약간 다릅니다. 기존 tsconfig에서 include부분만 `"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]`로 해도 잘 돌아갑니다!
- 이때 Header.tsx에서 potentially any라고 에러를 하나 띄우던데, 이건 strict 여부에 따라 생기고 안 생기고 하는 에러인 것 같습니다. 아마 작업할 때 안 떴었다면 include에 "src"만 있었으니 Header.tsx를 제대로 검사하지 않아서 그렇지 않았을까요...?

2022-12-19 15:47 UTC, emilyyoon3107 commented
interface랑 type 중에서는 interface를 더 권장한다고 되어 있기는 하네요...! [https://www.typescriptlang.org/play#example/types-vs-interfaces](url)
주요한 차이는 이렇다는 거 같아요
- interface는 open, type은 closed 
- extend하는 방식이 다르다
- error message가 다르게 뜰 때가 있다

2022-12-19 16:42 UTC, Limchansol commented
코멘트 남겨주신 부분들 수정했습니다. day 추가한 부분이 말씀해주신 내용과 일치하는지 확인 한번 부탁드려요!
지금 폴더 구조(context, lib 등)를 제 임의대로 만든 상태인데 괜찮은지도 봐주시면 감사하겠습니다.

2022-12-19 17:21 UTC, emilyyoon3107 reviewed
확인 완료했습니다!

2022-12-20 02:54 UTC, aylee2008 approved these changes
yarn.lock이 바뀐 이유는 제가 mac이라 darwin os를 쓰는데 다른 두 분은 win os를 쓰셔서 그런 것 같아요. 아마 누가 commit하느냐에 따라서 매번 바뀔 가능성이 높을듯 합니다..! 큰 문제는 아닐 듯 해요.

2022-12-20 03:48 UTC, emilyyoon3107 approved these changes

2022-12-20 03:49 UTC, merged