Header details
wafflestudio20-5/team9-web pull request #7
Opened 2022-12-24 08:20 UTC by Limchansol

- 헤더에 있는 각종 자잘한 버튼 간단하게 구현했습니다.
- 검색창(헤더에서 검색 버튼 누르면 나오길래) 레이아웃만 잡아놨습니다.
- modal 관련 컴포넌트(세부 검색창, 유저 정보 팝업 등에 사용) 추가했습니다. 나중에 할일 추가 팝업창 구현할 때도 쓸만할 것 같아서 만들어봤습니다!
- dropDown 관련 컴포넌트(헤더 버튼들에 사용) 추가했습니다.
- 컴포넌트가 많아진  관계로 일단 `component` 폴더에 `Header` 폴더 따로 생성해서 옮겨놓았습니다.
- 한번에 뭘 많이 만들어서 구멍난 부분이 많을 것 같아요. 특히 모달과 드롭다운...!😂피드백 주시면 감사하겠습니다!

2022-12-24 12:23 UTC, emilyyoon3107 commented on components/Header/Searchbar.tsx
> +            console.log('search listener add');
console.log 지워주세요...!

2022-12-24 12:23 UTC, emilyyoon3107 commented on lib/hooks/useModal.ts
> +}
useModal을 ModalContext에 합쳐서 놓으면 더 깔끔할 것 같아요!

2022-12-24 12:55 UTC, emilyyoon3107 commented
- 드롭다운이랑 모달을 각각 컴포넌트로 만드는 게 가독성 측면에서는 좋을 것 같아요!
- 모달 관련 함수들이 여기저기 퍼져있는 느낌이 좀 들어서 context 한 개에 모으면 훨씬 깔끔해질 것 같아요
- (이건 그냥 궁금증입니다) `<></>`를 사용하는 게 여러 개의 JSX element를 return해야 할 때 이외에도 장점이 있는 건가요? 관습처럼 쓰는 건가 싶어서요!
- search bar deatils 안에 있는 dropdown들은 바깥을 클릭했을 때 닫히는 기능이 제대로 작동하지 않습니다. ref를 사용한 감지 방식이 아직 완전히 이해되지는 않았는데 뭔가 modal 위에서 dropdown을 만들었을 때 eventListener가 잘 작동하지 않는 거 같아요. 어차피 modal보다 dropdown이 항상 더 위쪽(높은 z-index)에 올라오니까 dropdown도 backdrop으로 하되 z-index를 하나 올려줘도 될 것 같고요.
- z-index 쓸 일이 앞으로도 조금 더 있을 거 같아서 (ex. 새 일정 만들기 버튼, week page에서 겹치게 나오는 부분) 단위를 조금 더 크게 잡는 건 어떨까 싶습니다.

2022-12-24 13:04 UTC, Limchansol commented on components/Header/Header.tsx
> +    };
엇 저는 여태 두번째라고 이해하고 구현했습니다. 오늘 날짜는 Date쓰면 바로 얻을 수 있어서 굳이 저장해둘 필요가 없고, DateContext에 저장하는 날짜는 사용자가 보고 있는 날짜인 걸로요! 나중에 서버에서 일정을 받아온다거나 할 때 유저가 원하는 날짜가 무엇인지 저장해두고 있어야 올바른 일정을 불러올 수 있을 것 같기도 하고, 당장 헤더 중앙에서 보여주는 날짜도 유저가 현재 보고 있는(변동 가능한) 날짜여서요!

2022-12-25 14:15 UTC, Limchansol commented
늦어서 죄송합니다. 코멘트 주신 내용 반영하여 수정했습니다!
- 드롭다운 화살표 svg로 변경하고, 불필요한 코드는 삭제했습니다.
- 캘린더에서 사용되는 모달 디자인과 내용은 일관적이지 않은 것 같아서 `ModalFrame`으로 기초적인 디자인과 `backdrop`만 제공하고, 모달의 구체적인 내용은 별도의 컴포넌트로 구현하도록 했습니다...!
- 드롭다운은 원한다면 별도 컴포넌트로 빼지 않아도 되지만, 분리하는 편이 가독성이 더 좋을 것 같아서 각각의 드롭다운 컴포넌트들은 그대로 두었습니다. 다만 통일성을 위해 `DropDown`, `DropDownHeader`, `DropDownBody`를 사용하도록 변경했습니다!

2022-12-25 15:18 UTC, emilyyoon3107 reviewed
확인했습니다! CalendarTypeDropDown이 제 로컬에서는 글자 크기가 안 맞아서 넘어가던데 그거 말고는 더 문제될 부분 없어보여요! 고생 많으셨습니다!!

2022-12-26 01:34 UTC, aylee2008 requested changes
코드 양을 보니.. 정말 고생이 많으셨겠어요... 수고 많으셨습니다! 그리고 효정님이 꼼꼼하게 잘 comment해주신 것 같아요! 저는 조금만 첨언하겠습니다 :)

1. 글씨체가 뭔가 통일성이 없이 브라우저 default로 되는 것 같은데, 무난한 글씨체 하나 지정해서 한번에 적용해주시면 좋을 것 같아요! 디자인적인 부분을 많이 신경쓰는 건 아니지만.. 누가 보느냐에 따라 글씨체가 조금씩 달라질 수 있을 것 같아서 통일하는 게 좋을 것 같네요.
2. `DayinMonth.tsx`에서 `names overlap!` 부분의 주석은 이미 해결되었으므로 지워주시면 좋을 것 같습니다.

2022-12-26 16:35 UTC, Limchansol commented
- 코멘트 반영하여 수정했습니다!
- 폰트 [나눔고딕](https://fonts.google.com/specimen/Nanum+Gothic?subset=korean&noto.script=Kore)으로 적용했습니다. 원래 `body`에 달려고 했는데 `form`과 관련된 태그들에는 폰트 자동 상속이 불가해서 전체 요소(`*`)에 적용해두었습니다.
- 자주 쓰이는 색깔이 몇 가지 있는 것 같아서 `variables.scss`에 모아두고 다른 파일에서는 `@use`로 가져오도록 했습니다.

2022-12-27 03:49 UTC, aylee2008 approved these changes
나눔고딕 예쁘네요. 저도 효정님처럼 원래 `캘린더` 부분이 깨졌었는데, 이젠 안 깨집니다!
수고하셨어요!

2022-12-27 14:42 UTC, merged